build: false

environment:
    PYTHON: "C:\\Python37"

    CONAN_REFERENCE: "bzip2/1.0.6"
    CONAN_USERNAME: "conan"
    CONAN_LOGIN_USERNAME: "conanbot"
    CONAN_CHANNEL: "stable"
    CONAN_UPLOAD: "https://api.bintray.com/conan/conan-community/conan"
    CONAN_STABLE_BRANCH_PATTERN: "release/*"

    matrix:
        - MINGW_CONFIGURATIONS: "8@x86@dwarf2@posix"
        - MINGW_CONFIGURATIONS: "7@x86@dwarf2@posix"
        - MINGW_CONFIGURATIONS: "6@x86@dwarf2@posix"
        - MINGW_CONFIGURATIONS: "5@x86@dwarf2@posix"
        - MINGW_CONFIGURATIONS: "4.9@x86@dwarf2@posix"
        - MINGW_CONFIGURATIONS: "8@x86_64@seh@posix"
        - MINGW_CONFIGURATIONS: "7@x86_64@seh@posix"
        - MINGW_CONFIGURATIONS: "6@x86_64@seh@posix"
        - MINGW_CONFIGURATIONS: "5@x86_64@seh@posix"
        - MINGW_CONFIGURATIONS: "4.9@x86_64@seh@posix"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
